receivers:
  otlp:
    protocols:
      grpc:
      http:
  awsfirehose:
    endpoint: 0.0.0.0:4433
    record_type: cwmetrics

processors:
  batch:
    send_batch_size: 4000
    send_batch_max_size: 4000
    timeout: 10s

exporters:
  otlp:
    endpoint: "promscale:9202"
    tls:
      insecure: true
    sending_queue:
      queue_size: 1000000
    timeout: 10s
  logging:
    loglevel: debug
  prometheusremotewrite:
    endpoint: "http://promscale:9201/write"
    resource_to_telemetry_conversion:
      enabled: true # Convert resource attributes to metric labels
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [awsfirehose]
      processors: [batch]
      exporters: [prometheusremotewrite]
