apiVersion: 1

deleteDatasources:
  - name: promscale-metrics
    ordId: 1
  - name: promscale-traces
    orgId: 1

datasources:
  - name: promscale-metrics
    type: prometheus
    access: proxy
    uid: prom-metrics
    orgId: 1
    url: http://promscale:9201
    editable: true
    version: 1

  - name: promscale-traces
    type: jaeger
    access: proxy
    uid: prom-traces
    orgId: 1
    url: http://promscale:9201
    editable: true
    version: 1
