apiVersion: 1

deleteDatasources:
  - name: promscale-metrics
    ordId: 1
  - name: promscale-traces
    orgId: 1

datasources:
  - name: promscale-metrics
    type: prometheus
    access: proxy
    uid: prom-metrics
    orgId: 1
    url: http://promscale:9201
    editable: true
    version: 1

  - name: promscale-traces
    type: jaeger
    access: proxy
    uid: prom-traces
    orgId: 1
    url: http://promscale:9201
    editable: true
    version: 1

  - name: promscale-sql
    uid: prom-sql
    type: postgres
    version: 1
    access: proxy
    orgId: 1
    editable: true
    url: http://timescaledb:5432
    database: postgres
    user: postgres
    secureJsonData:
      password: "password"
    jsonData:
      sslmode: "disable" # disable/require/verify-ca/verify-full
      timescaledb: true
