{
 "title": "firefly-dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "FunctionName", "label": "FunctionName", "query": { "query": "Invocations" } }
  ]
 },
 "panels": [
  {
   "title": "Memory utilization",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_utilization{function_name=\"$FunctionName\", quantile=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invocations",
   "type": "stat",
   "description": "Per minute",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Invocations_count{Resource=\"$FunctionName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cold starts",
   "type": "stat",
   "description": "Per day",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time(init_duration_count{function_name=\"$FunctionName\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "service": "$FunctionName" }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "Per hour",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(Errors{Resource=\"$FunctionName\", quantile=\"1\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invocations",
   "type": "timeseries",
   "description": "Per minute average",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "Invocations_count{Resource=\"$FunctionName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "Errors{Resource=\"$FunctionName\", quantile=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throttles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "Throttles{Resource=\"$FunctionName\", quantile=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Concurrent Executions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "ConcurrentExecutions{Resource=\"$FunctionName\", quantile=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "targets": [
    { "service": "$FunctionName" }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "targets": [
    { "service": "$FunctionName" }
   ]
  }
 ]
}