{
 "title": "firefly-general",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Invocations",
   "type": "timeseries",
   "description": "Per minute",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "  SELECT sum(value) AS invocations, val(\"Resource_id\") AS service_name, time\n  FROM \"Invocations_count\"\n  WHERE time > TO_TIMESTAMP(${__from} / 1000) AND val(\"Resource_id\") IS NOT NULL\n  GROUP BY service_name, time\n  ORDER BY time asc;"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Per minute",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "  SELECT value AS errors, val(\"Resource_id\") AS service_name, time\n  FROM \"Errors_sum\"\n  WHERE time > TO_TIMESTAMP(${__from} / 1000) AND val(\"Resource_id\") IS NOT NULL\n  ORDER BY time asc;"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "Per invocation",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT max(duration_ms) AS max_duration, service_name, start_time AS time\nFROM span\nWHERE start_time > TO_TIMESTAMP(${__from} / 1000) AND service_name = span_name\nGROUP BY service_name, time\nORDER BY time asc;"
    }
   ]
  },
  {
   "title": "Functions",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "WITH invocations AS (\n  SELECT sum(value) AS invocations, val(\"Resource_id\") AS service_name\n  FROM \"Invocations_count\"\n  WHERE time > TO_TIMESTAMP(${__from} / 1000) AND val(\"Resource_id\") IS NOT NULL\n  GROUP BY service_name\n), errors AS (\n  SELECT sum(value) AS errors, val(\"Resource_id\") AS service_name\n  FROM \"Errors_sum\"\n  WHERE time > TO_TIMESTAMP(${__from} / 1000) AND val(\"Resource_id\") IS NOT NULL\n  GROUP BY service_name\n), duration AS (\n  SELECT trace_id, max(duration_ms) as max_duration, service_name\n  FROM span\n  WHERE start_time > TO_TIMESTAMP(${__from} / 1000)\n  GROUP BY service_name, trace_id\n)\nSELECT  invocations.service_name AS \"Function\",\n        invocations.invocations AS \"Invocations\",\n        avg(duration.max_duration) AS \"Duration\",\n        errors.errors AS \"Errors\"\nFROM invocations                       \nLEFT JOIN errors ON invocations.service_name = errors.service_name\nLEFT JOIN duration ON invocations.service_name = duration.service_name\nGROUP BY \"Function\", \"Invocations\", \"Errors\";\n"
    }
   ]
  }
 ]
}